# -*- coding: utf-8 -*-
"""TF-DiazAlejandro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11c2UvTM2qiY23LfhzdqbS7yelI4YmUj7
"""

import onnxruntime as ort
import numpy as np
import gradio as gr
from PIL import Image
import time

ruta_modelo_onnx = "modelo_senas_v4.onnx"
letras = "abcdefghiklmnopqrstuvwxy"
clases =[letra.upper() for letra in letras]

opciones_sesion = ort.SessionOptions()
opciones_sesion.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
sesion_ort = ort.InferenceSession(ruta_modelo_onnx, opciones_sesion)
nombre_entrada_ort = sesion_ort.get_inputs()[0].name
nombre_salida_ort = sesion_ort.get_outputs()[0].name

def predecir_sena(imagen):
    if imagen is None:
        return "por favor sube una imagen valida."

    imagen_gris = imagen.convert('L').resize((28, 28))
    matriz_imagen = np.array(imagen_gris, dtype=np.float32) / 255.0
    tensor_entrada = np.expand_dims(np.expand_dims(matriz_imagen, axis=-1), axis=0)

    tiempo_inicio = time.perf_counter()
    salida_ort = sesion_ort.run([nombre_salida_ort], {nombre_entrada_ort: tensor_entrada})
    tiempo_inferencia = (time.perf_counter() - tiempo_inicio) * 1000

    indice_prediccion = np.argmax(salida_ort[0][0])
    confianza = np.max(salida_ort[0][0])
    letra_predicha = clases[indice_prediccion]

    return f"Letra predicha: {letra_predicha} \nConfianza: {confianza*100:.2f}% \nLatencia ONNX: {tiempo_inferencia:.2f} ms"

interfaz = gr.Interface(
    fn=predecir_sena,
    inputs=gr.Image(type="pil", label="Sube una imagen de una seña manual"),
    outputs=gr.Textbox(label="Resultado de la inferencia optimizada"),
    title="Reconocimiento de Lenguaje de Señas - Motor ONNX",
    description="Despliegue de la versión final del modelo utilizando ONNX Runtime para garantizar una latencia mínima en entornos de producción."
)

if __name__ == "__main__":
    interfaz.launch(server_name="0.0.0.0", server_port=7860)